// #define SECRET_SSID "Kanata Iphone SE"
// #define SECRET_PASS "QQjv-mqH6-cCsu-Iegu"
// #define SECRET_SSID "transponder snail 174"
// #define SECRET_PASS "Mathisfun#1"
#define SECRET_SSID "MOTOCB22"
#define SECRET_PASS "f6a85u4f6a"